// voting-card/src/components/voting-result.component.ts
import { OnInit } from '@angular/core';
import { Component, Input } from '@angular/core'

@Component({
  selector: 'result',
  template:  `
    <div *ngFor="let option of votes; index as i">
        {{i+1}}. {{option.option}} - {{option.count}} votes ({{((option.count / total)*100).toFixed(0)}}%)
    </div>
`
})

export class VotingResultComponent implements OnInit {
    @Input() votes: { option: string; count: number; }[] = [];
    total = 0;

    ngOnInit() {
        for(var i=0; i<this.votes.length; i++){
            this.total += this.votes[i].count;
        }
    }
}

// voting-card/src/components/voting-result.vue
<template>
    <div id="result">
        <div 
            v-for="(option, index) in votes"
            :key="option.option"
        >
            {{index+1}}. {{option.option}} - {{option.count}} votes ({{((option.count / total)*100).toFixed(0)}}%)
        </div>
    </div>
</template>

<script>
    export default {
        props: ['votes'],
        data: () => ({
            total: 0
        }),
        created: function (){
            for(var i=0; i<this.votes.length; i++){
                this.total += this.votes[i].count;
            }
        }
    }
</script>

<style>

</style>
