// voting-card/src/components/voting-booth.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core'

@Component({
  selector: 'booth',
  template: `
    <button class="choice" *ngFor="let option of options; index as i" (click)="select.emit(i)">
        {{ option }}
    </button>
  `,
  styles:[
    `
        .choice{
            margin: 10px;
        }
`
  ]
})

export class VotingBoothComponent {
    @Input() options: string[] | undefined
    @Output() select = new EventEmitter()
}

// voting-card/src/components/voting-booth.vue
<template>
    <div id="booth">
        <button 
            class="choices"
            v-for="(option, index) in options" 
            :key="option"
            @click="$emit('select', index)"
        >
            {{ option }}
        </button>
    </div>
</template>

<script>

    export default {
        props: ['options']
    }

</script>

<style>
    .choices{
        margin: 10px;
    }  
</style>
