// react/voting-card/src/components/VotingBooth.js
//Opções da votação

import React from 'react'

export default function VotingBooth(props) {

    const choices = props.choices.map((option, index) => (
        <button key={option.text} onClick={() => props.onSelect(index)}>
        {option.text}
      </button>
    ))
      

    return (
        <div className="choices">
            { choices }
        </div>
    )
}

// voting-card/src/components/voting-booth.vue
<template>
    <div id="booth">
        <button 
            class="choices"
            v-for="(option, index) in options" 
            :key="option"
            @click="$emit('select', index)"
        >
            {{ option }}
        </button>
    </div>
</template>

<script>

    export default {
        props: ['options']
    }

</script>

<style>
    .choices{
        margin: 10px;
    }  
</style>
