// voting-card/src/App.vue
<template>
  <div id="app">
    <Card
      :title="title"
      :state="state"
      :votes="votes"
    ></Card>
  </div>
</template>

<script>
  import Card from './components/voting-card.vue'

  export default {
    name: 'App',
    data: () => ({
      title: "Segue o relator?",
      state: "open",
      votes: [
        {
          "option": "Sim",
          "count": 8
        },
        {
          "option": "Não",
          "count": 3
        }
      ]
    }),
    components: {
      Card
    }
  }
</script>

<style>

</style>

// voting-card/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<card title="Segue o relator?" state="open" [votes]="options" ></card>'
})
export class AppComponent {
  title = 'voting-card';
  options = [
    {
        option: 'Sim',
        count: 8,
    },
    {
        option: 'Não',
        count: 3
    }
]
}
